### ISSUE TITLE
Decorative cover for top hole

### ISSUE THREAD

**Issue by ADKMechETECH** [atrushing/Mini_Stealth#1]
Maybe I missed it, but is there a decorative (or plain) cover for the top hole like there was for V1?

**Comment by atrushing** [comment]
I have added the two versions in the *Common Parts* folder. The Sherpa extruders sit too close to the shroud so these hole covers will not fit with them unless using my VZ RIDGA version of the Sherpa Micro.

**Comment by ADKMechETECH** [comment]
Awesome, thank you!
