### ISSUE TITLE
x_carriage_frames_Beacon3D_MGN12.stl Mini Sherpa

### ISSUE THREAD

**Issue by chadakenn** [atrushing/Mini_Stealth#2]
x_carriage_frames_Beacon3D_MGN12.stl for the Mini Sherpa and bltouch both parts dont sit level on the bed also any way to hit eddy in the middle

**Comment by atrushing** [comment]
I probably need to double check all of the x-carriage pairs to see how many need to be fixed. For now, you could right click the x-frame .stl in the slicer and use the [Split] >> [To Objects] tool and the raised one should drop down to the build plate.
Thanks for letting me know about the issue.

**Comment by chadakenn** [comment]
> I probably need to double check all of the x-carriage pairs to see how many need to be fixed. For now, you could right click the x-frame .stl in the slicer and use the [Split] >> [To Objects] tool and the raised one should drop down to the build plate. Thanks for letting me know about the issue.

i just dropped it down it was only one layer so hopfully itll still fit

**Comment by atrushing** [comment]
Yeah, the one missing layer won't effect the geometry of the assembled x-carriage.
